<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20190215 14:22:35.277" generator="Robot 3.0.4 (Python 2.7.15 on win32)">
<suite source="D:\Assesment Portal\Mobile\test_mobile.robot" id="s1" name="Test Mobile">
<test id="s1-t1" name="Test">
<kw name="setup and open android phone1">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.</doc>
<arguments>
<arg>${APPIUM_SERVER1}</arg>
<arg>platformName=android</arg>
<arg>platformVersion=7.0</arg>
<arg>deviceName=f1232233</arg>
<arg>automationName=uiautomator2</arg>
<arg>appPackage=com.samsung.android.contacts</arg>
<arg>newCommandTimeout=2500</arg>
<arg>appActivity=com.android.dialer.DialtactsActivity</arg>
</arguments>
<assign>
<var>${androiddriver1}</var>
</assign>
<msg timestamp="20190215 14:22:38.407" level="INFO">Could not connect to port 4723 on host 0.0.0.0</msg>
<msg timestamp="20190215 14:22:38.407" level="INFO">Could not get IP address for host: 0.0.0.0</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20190215 14:22:38.437" level="FAIL">No application is open</msg>
<status status="FAIL" endtime="20190215 14:22:38.437" starttime="20190215 14:22:38.427"></status>
</kw>
<msg timestamp="20190215 14:22:38.437" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20190215 14:22:38.447" level="FAIL">URLError: &lt;urlopen error [Errno 10049] The requested address is not valid in its context&gt;</msg>
<status status="FAIL" endtime="20190215 14:22:38.447" starttime="20190215 14:22:38.397"></status>
</kw>
<status status="FAIL" endtime="20190215 14:22:38.447" starttime="20190215 14:22:38.397"></status>
</kw>
<status status="FAIL" endtime="20190215 14:22:38.447" critical="yes" starttime="20190215 14:22:38.397">URLError: &lt;urlopen error [Errno 10049] The requested address is not valid in its context&gt;</status>
</test>
<doc>This script starts apps on two phones</doc>
<status status="FAIL" endtime="20190215 14:22:38.447" starttime="20190215 14:22:35.287"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Test Mobile" pass="0">Test Mobile</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190215 14:22:38.437" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
